name: $(date:yyyyMMdd)$(rev:.r)

trigger: 
- main

pool:
  vmImage: ubuntu-18.04

jobs:
- job: Job_0
  displayName: 'Build ARM Package'
  steps:
  - bash: |
     curl -Lo bicep.bin https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
     chmod +x ./bicep.bin
    displayName: 'Install Azure Bicep'

  - bash: |
     bicep build --outdir $(Build.ArtifactStagingDirectory) main.bicep
     cp deploymentParameters.json $(Build.ArtifactStagingDirectory)
    displayName: 'Build ARM Template'
 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish ARM Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
    condition: succeeded()
