name: $(date:yyyyMMdd)$(rev:.r)

trigger: 
- main

pool:
  vmImage: ubuntu-18.04
  workspace:
    clean: all

jobs:
- job: Job_0
  displayName: 'Build and Test'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Nuget Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      projects: '**/*.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/Processor.sln'
      arguments: '--no-build --logger trx --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results'
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: DotNetCoreCLI@2
    displayName: 'Build Processor Package'
    inputs:
      command: publish
      publishWebProjects: False
      projects: './src/Processor/Processor.csproj'
      arguments: '-c Release -r win10-x64 --self-contained true --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True 
 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Processor Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
    condition: succeeded()